.PHONY: install

install:
	python -m pip install -r requirements.txt

.PHONY: run-validator
run-validator: 
	cd neurons && \
	pm2 start validator.py --name validator --interpreter python3 -- \
	--netuid 28 \
	--subtensor.network finney \
	--wallet.name validator_key \
	--wallet.hotkey validator_hotkey \
	--subtensor.chain_endpoint wss://entrypoint-finney.opentensor.ai:443 \
	--logging.debug 

.PHONY: run-miner
run-miner: 
	cd neurons && \
	pm2 start miner.py --name miner --interpreter python3 -- \
	--netuid 28 \
	--axon.port 8092 \
	--subtensor.network finney \
	--wallet.name miner_key \
	--wallet.hotkey miner_hotkey \
	--subtensor.chain_endpoint wss://entrypoint-finney.opentensor.ai:443 \
	--logging.debug 
