.PHONY: install

install:
	python -m pip install -r requirements.txt

.PHONY: run-validator
run-validator: 
	cd neurons && \
	pm2 start validator.py --name validator --interpreter python3 -- \
	--netuid 39 \
	--subtensor.network test \
	--wallet.name test_validator \
	--wallet.hotkey test_validator_h1 \
	--subtensor.chain_endpoint wss://test.finney.opentensor.ai:443 \
	--logging.debug 

.PHONY: run-miner
run-miner: 
	cd neurons && \
	pm2 start miner.py --name miner --interpreter python3 -- \
	--netuid 39 \
	--axon.port 8092 \
	--subtensor.network test \
	--wallet.name test_miner \
	--wallet.hotkey test_miner_h2 \
	--subtensor.chain_endpoint wss://test.finney.opentensor.ai:443 \
	--logging.debug 
